# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'KYHandMade' do

  use_frameworks!
 pod 'SwiftyJSON'
 pod 'Alamofire'
 pod 'Kingfisher'
 pod 'SnapKit'
 pod 'SVProgressHUD'
 pod 'SDCycleScrollView'
 pod 'MJRefresh'
 pod 'DOPDropDownMenu'
 pod 'DynamicColor'
 pod 'FMDB'
 pod 'SDAutoLayout'
end
